application:
  name: hasura
  project: testQoveryHasura
  cloud_region: aws/eu-west-3
databases:
- type: postgresql
  version: "11"
  name: my-postgresql-database
routers:
- name: main
  routes:
  - application_name: hasura
    paths:
    - /*
